"use client";
import {useEffect,useState} from "react";import {supabase} from "../../lib/supabase";
const PASS_HASH="a02efd51ae07dcf357d37688eb3776742c6546f3c5ba38a3e4a2d853a2598d60";
async function hash(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,"0")).join("")}
export default function Admin(){const [authed,setAuthed]=useState(false);const [password,setPassword]=useState("");const [movies,setMovies]=useState<any[]>([]);const [form,setForm]=useState({title:"",description:"",year:"",genre:"",duration:"",is_public:true});const [poster,setPoster]=useState<File|null>(null);const [video,setVideo]=useState<File|null>(null);const [msg,setMsg]=useState("");
async function load(){const {data}=await supabase.from("movies").select("*").order("created_at",{ascending:false});setMovies(data||[])}
useEffect(()=>{if(sessionStorage.getItem("movie_admin")!=="1")return;setAuthed(true);load()},[]);
async function unlock(){if(await hash(password)===PASS_HASH){sessionStorage.setItem("movie_admin","1");setAuthed(true);setPassword("");load()}else setMsg("Wrong admin password.")}
async function upload(){setMsg("");if(!poster||!video)return setMsg("Poster and video are required.");if(!form.title.trim())return setMsg("Title is required.");const pid=crypto.randomUUID()+"-"+poster.name.replace(/[^a-zA-Z0-9._-]/g,"_");const vid=crypto.randomUUID()+"-"+video.name.replace(/[^a-zA-Z0-9._-]/g,"_");const p=await supabase.storage.from("movie-posters").upload(pid,poster,{cacheControl:"3600"});if(p.error)return setMsg(p.error.message);const v=await supabase.storage.from("movie-videos").upload(vid,video,{cacheControl:"3600"});if(v.error)return setMsg(v.error.message);const poster_url=supabase.storage.from("movie-posters").getPublicUrl(pid).data.publicUrl;const video_url=supabase.storage.from("movie-videos").getPublicUrl(vid).data.publicUrl;const r=await supabase.from("movies").insert({title:form.title,description:form.description,year:form.year?Number(form.year):null,genre:form.genre,duration:form.duration?Number(form.duration):null,is_public:form.is_public,poster_url,video_url}).select().single();if(r.error)return setMsg(r.error.message);setMovies(x=>[r.data,...x]);setForm({title:"",description:"",year:"",genre:"",duration:"",is_public:true});setPoster(null);setVideo(null);setMsg("Movie uploaded.")}
if(!authed)return <div className="auth"><div className="panel"><p className="eyebrow">MOVIE NIGHT</p><h1>Admin</h1><p className="muted">Enter the admin password to manage movies.</p><input type="password" placeholder="Admin password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==="Enter"&&unlock()}/><button className="button" onClick={unlock}>Unlock admin</button>{msg&&<p className="notice">{msg}</p>}</div></div>;
return <section><div className="toolbar"><div><p className="eyebrow">CONTROL CENTER</p><h1>Movie library</h1></div></div><div className="admin-grid"><div className="panel"><h2>Add movie</h2><input placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="row"><input placeholder="Year" value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/><input placeholder="Genre" value={form.genre} onChange={e=>setForm({...form,genre:e.target.value})}/><input placeholder="Minutes" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/></div><label>Poster<input type="file" accept="image/*" onChange={e=>setPoster(e.target.files?.[0]||null)}/></label><label>Video<input type="file" accept="video/*" onChange={e=>setVideo(e.target.files?.[0]||null)}/></label><button className="button" onClick={upload}>Upload movie</button>{msg&&<p className="notice">{msg}</p>}</div><div className="panel"><h2>Current movies</h2>{movies.map(m=><div className="admin-item" key={m.id}><span>{m.title}</span><button onClick={async()=>{await supabase.from("movies").delete().eq("id",m.id);setMovies(x=>x.filter(a=>a.id!==m.id))}}>Delete</button></div>)}</div></div></section>}
