"use client";
import {useEffect,useRef,useState} from "react";import {Upload} from "tus-js-client";import {supabase} from "../../lib/supabase";
const PASS_HASH="a02efd51ae07dcf357d37688eb3776742c6546f3c5ba38a3e4a2d853a2598d60";
const PROJECT_ID="txnisvhvacftvndzsnwa";
async function hash(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,"0")).join("")}
function uploadVideo(path:string,file:File,onProgress:(p:number)=>void){return new Promise<void>((resolve,reject)=>{const upload=new Upload(file,{endpoint:`https://${PROJECT_ID}.storage.supabase.co/storage/v1/upload/resumable`,retryDelays:[0,3000,5000,10000,20000],headers:{authorization:`Bearer ${process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!}`},uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,chunkSize:6*1024*1024,metadata:{bucketName:"movie-videos",objectName:path,contentType:file.type||"video/mp4",cacheControl:"3600"},onError:error=>reject(error),onProgress:(uploaded,total)=>onProgress(Math.round(uploaded/total*100)),onSuccess:()=>resolve()});upload.start()})}
export default function Admin(){const [authed,setAuthed]=useState(false);const [password,setPassword]=useState("");const [movies,setMovies]=useState<any[]>([]);const [form,setForm]=useState({title:"",description:"",year:"",genre:"",duration:"",is_public:true});const [poster,setPoster]=useState<File|null>(null);const [video,setVideo]=useState<File|null>(null);const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);const posterRef=useRef<HTMLInputElement>(null);const videoRef=useRef<HTMLInputElement>(null);
async function load(){const {data,error}=await supabase.from("movies").select("*").order("created_at",{ascending:false});if(error){setMsg(error.message);return}setMovies(data||[])}
useEffect(()=>{if(sessionStorage.getItem("movie_admin")==="1"){setAuthed(true);load()}},[]);
async function unlock(){setMsg("");if(await hash(password)===PASS_HASH){sessionStorage.setItem("movie_admin","1");setAuthed(true);setPassword("");await load()}else setMsg("Wrong admin password.")}
async function upload(){if(busy)return;setMsg("");if(!poster||!video)return setMsg("Select both a poster and a video first.");if(!form.title.trim())return setMsg("Title is required.");if(video.size>50*1024*1024)return setMsg("This Supabase project allows videos up to 50 MB. Choose a smaller video or raise the Storage limit.");setBusy(true);try{
 const pid=crypto.randomUUID()+"-"+poster.name.replace(/[^a-zA-Z0-9._-]/g,"_");const vid=crypto.randomUUID()+"-"+video.name.replace(/[^a-zA-Z0-9._-]/g,"_");
 setMsg("Uploading poster...");const p=await supabase.storage.from("movie-posters").upload(pid,poster,{cacheControl:"3600",upsert:false,contentType:poster.type});if(p.error)throw new Error("Poster upload failed: "+p.error.message);
 setMsg("Uploading video: 0%");await uploadVideo(vid,video,p=>setMsg(`Uploading video: ${p}%`));
 setMsg("Saving movie...");const poster_url=supabase.storage.from("movie-posters").getPublicUrl(pid).data.publicUrl;const video_url=supabase.storage.from("movie-videos").getPublicUrl(vid).data.publicUrl;
 const r=await supabase.from("movies").insert({title:form.title.trim(),description:form.description,year:form.year?Number(form.year):null,genre:form.genre.trim(),duration:form.duration?Number(form.duration):null,is_public:form.is_public,poster_url,video_url}).select().single();
 if(r.error){await supabase.storage.from("movie-posters").remove([pid]);await supabase.storage.from("movie-videos").remove([vid]);throw new Error("Saving movie failed: "+r.error.message);}
 setMovies(x=>[r.data,...x]);setForm({title:"",description:"",year:"",genre:"",duration:"",is_public:true});setPoster(null);setVideo(null);if(posterRef.current)posterRef.current.value="";if(videoRef.current)videoRef.current.value="";setMsg("✅ Movie uploaded successfully.");
}catch(e){setMsg(e instanceof Error?e.message:"Upload failed.");}finally{setBusy(false)}}
if(!authed)return <div className="auth"><div className="panel"><p className="eyebrow">MOVIE NIGHT</p><h1>Admin</h1><p className="muted">Enter the admin password to manage movies.</p><input type="password" placeholder="Admin password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==="Enter"&&unlock()}/><button className="button" onClick={unlock}>Unlock admin</button>{msg&&<p className="notice">{msg}</p>}</div></div>;
return <section><div className="toolbar"><div><p className="eyebrow">CONTROL CENTER</p><h1>Movie library</h1></div></div><div className="admin-grid"><div className="panel"><h2>Add movie</h2><input placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="row"><input placeholder="Year" value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/><input placeholder="Genre" value={form.genre} onChange={e=>setForm({...form,genre:e.target.value})}/><input placeholder="Minutes" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/></div><label>Poster<input ref={posterRef} type="file" accept="image/*" onChange={e=>setPoster(e.target.files?.[0]||null)}/></label><label>Video<input ref={videoRef} type="file" accept="video/*" onChange={e=>setVideo(e.target.files?.[0]||null)}/></label><button className="button" disabled={busy} onClick={upload}>{busy?"Uploading...":"Upload movie"}</button>{msg&&<p className="notice">{msg}</p>}</div><div className="panel"><h2>Current movies</h2>{movies.map(m=><div className="admin-item" key={m.id}><span>{m.title}</span><button onClick={async()=>{const r=await supabase.from("movies").delete().eq("id",m.id);if(r.error){setMsg(r.error.message);return}setMovies(x=>x.filter(a=>a.id!==m.id))}}>Delete</button></div>)}</div></div></section>}